# ruff: noqa: E501
from src.data_pipeline.transform.PipelineTransformer import PipelineTransformer
from src.data_pipeline.transform.templates.arkleg.LegislatorTransformer import (
    LegislatorTransformer,
)

input_val = {
    "title": ["Senator Cecile Bledsoe (R)"],
    "phone": [""],
    "email": None,
    "address": [
        "\n\n709 Sky Mountain Dr.,                                Rogers,\n                                72757\n                            \n"
    ],
    "district": ["3"],
    "seniority": ["1"],
    "public_service": ["House 1999,  2001,  2003,  Senate 2009,  2011,  2013,  2015,  2017"],
    "committees": [
        "\n                                        PUBLIC HEALTH, WELFARE AND LABOR COMMITTEE - SENATE\n                                    ",
        "\n                                        ALC-CLAIMS REVIEW\n                                    ",
        "\n                                         JBC-CLAIMS\n                                    ",
        "\n                                         JBC-SPECIAL LANGUAGE\n                                    ",
        "\n                                        ALC-ARKANSAS HEALTH INSURANCE MARKETPLACE OVERSIGHT SUBCOMMITTEE\n                                    ",
        "\n                                        ALC-PEER\n                                    ",
        "\n                                        ALC-POLICY MAKING\n                                    ",
        "\n                                        ALC-REVIEW\n                                    ",
        "\n                                        ARKANSAS HEALTH INSURANCE MARKETPLACE LEGISLATIVE OVERSIGHT COMMITTEE\n                                    ",
        "\n                                        ARKANSAS LEGISLATIVE COUNCIL (ALC)\n                                    ",
        "\n                                        ENERGY - JOINT\n                                    ",
        "\n                                        INSURANCE & COMMERCE - SENATE\n                                    ",
        "\n                                        JOINT BUDGET COMMITTEE\n                                    ",
        "\n                                        JOINT BUDGET COMMITTEE - PRE-FISCAL SESSION BUDGET HEARINGS\n                                    ",
        "\n                                        LEGISLATIVE JOINT AUDITING\n                                    ",
        "\n                                        LEGISLATIVE JOINT AUDITING-MEDICAID SUBCOMMITTEE\n                                    ",
        "\n                                        LEGISLATIVE JOINT AUDITING-STATE AGENCIES\n                                    ",
        "\n                                        SENATE RULES, RESOLUTIONS & MEMORIALS\n                                    ",
        "\n                                        STATE & PUBLIC SCHOOL LIFE & HEALTH INSURANCE TASK FORCE\n                                    ",
        "\n                                        PUBLIC HEALTH - SENATE HEALTH SERVICES\n                                    ",
        "\n                                        PUBLIC HEALTH - SENATE HUMAN SERVICES SUBCOMMITTEE\n                                    ",
        "\n                                        PUBLIC HEALTH - SENATE LABOR & ENVIRONMENT SUBCOMMITTEE\n                                    ",
    ],
    "committee_links": [
        "/Committees/Detail?code=430&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=004&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=009&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=028&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=032&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=020&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=050&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=010&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=131&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=000&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=510&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=490&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=005&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=007&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=905&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=931&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=920&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=952&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=461&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=428&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=427&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=438&ddBienniumSession=2017%2F2017R",
    ],
    "rel_url": "legislator/legislator.v3.html",
    "base_url": "/stem/",
}

output_val = {
    "party": "r",
    "f_name": "cecile",
    "l_name": "bledsoe",
    "chamber": "senate",
    "phone": None,
    "address": "709 sky mountain dr., rogers, 72757",
    "district": 3,
    "seniority": 1,
    "public_service": "house 1999, 2001, 2003, senate 2009, 2011, 2013, 2015, 2017",
    "committees": [
        "public health, welfare and labor committee - senate",
        "alc-claims review",
        "jbc-claims",
        "jbc-special language",
        "alc-arkansas health insurance marketplace oversight subcommittee",
        "alc-peer",
        "alc-policy making",
        "alc-review",
        "arkansas health insurance marketplace legislative oversight committee",
        "arkansas legislative council (alc)",
        "energy - joint",
        "insurance & commerce - senate",
        "joint budget committee",
        "joint budget committee - pre-fiscal session budget hearings",
        "legislative joint auditing",
        "legislative joint auditing-medicaid subcommittee",
        "legislative joint auditing-state agencies",
        "senate rules, resolutions & memorials",
        "state & public school life & health insurance task force",
        "public health - senate health services",
        "public health - senate human services subcommittee",
        "public health - senate labor & environment subcommittee",
    ],
    "committee_links": [
        "/Committees/Detail?code=430&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=004&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=009&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=028&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=032&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=020&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=050&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=010&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=131&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=000&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=510&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=490&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=005&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=007&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=905&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=931&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=920&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=952&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=461&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=428&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=427&ddBienniumSession=2017%2F2017R",
        "/Committees/Detail?code=438&ddBienniumSession=2017%2F2017R",
    ],
    "rel_url": "legislator/legislator.v3.html",
    "base_url": "/stem/",
}


class TestLegislatorTransformer:
    def test_legislator_transformer_success(self):
        transformer = PipelineTransformer()
        result = transformer.transform_content(LegislatorTransformer, input_val)

        assert result == output_val
