-- =========================================
-- Bootstrap script for a fresh PostgreSQL instance
-- Usage: psql -v VAR=value -f bootstrap_arwd.sql
-- =========================================
ALTER SYSTEM SET log_statement = 'ddl';
SELECT pg_reload_conf();

CREATE DATABASE :"DB_NAME" ENCODING 'UTF8';
ALTER DATABASE :"DB_NAME" SET timezone TO 'UTC';

CREATE ROLE :"ADMIN_USER" WITH LOGIN PASSWORD :'ADMIN_PASS';

ALTER DATABASE :"DB_NAME" OWNER TO :"ADMIN_USER";

CREATE ROLE :"SCRAPER_USER" WITH LOGIN PASSWORD :'SCRAPER_PASS';

\c :"DB_NAME"

CREATE SCHEMA IF NOT EXISTS :"SCRAPER_SCHEMA" AUTHORIZATION :"ADMIN_USER";

GRANT ALL PRIVILEGES ON SCHEMA :"SCRAPER_SCHEMA" TO :"ADMIN_USER";

GRANT USAGE ON SCHEMA :"SCRAPER_SCHEMA" TO :"SCRAPER_USER";

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA :"SCRAPER_SCHEMA" TO :"SCRAPER_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA :"SCRAPER_SCHEMA"
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"SCRAPER_USER";
ALTER ROLE :"SCRAPER_USER" CONNECTION LIMIT 5;

\dn+  -- show schemas and privileges
\du    -- show roles and privileges
